version: '3.4'

services:
  prusalink:
    build: .
    restart: unless-stopped
    #network_mode: host
    devices:
      # use `python3 -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - ./prusalink:/home/prusalink
      - type: bind
        source: ./prusalink.ini
        target: /etc/prusalink/prusalink.ini
    ports:
      - 8008:8080
    stdin_open: true
    tty: true
    #entrypoint: /bin/bash
